Options:
  Prefix: "&6&lSkyblock &8Â»"
  HelpGUI: false
  SpawnerMultiplier: 4
  XpMultiplier: 4
  EnableIsTop: true
  Level1Size: 25
  Level2Size: 50
  Level3Size: 75
  IslandHomeMainCommand: true
Inventories:
  Boosters: "&e&lIsland Boosters"
  Missions: "&e&lIsland Mission"
  Upgrades: "&e&lIsland Upgrades"
  Warp: "&e&lIsland Warps"
  Members: "&7&lIsland Members"
Upgrades:
  Members:
    1: 9
    2: 18
    3: 27
  Warps:
    1: 1
    2: 3
    3: 5
UpgradeCost:
  Size:
    1: 50
    2: 75
  Members:
    1: 40
    2: 60
  Warps:
    1: 20
    2: 40
OreGen:
  # List of Material Names https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
  - COBBLESTONE:30
  - IRON_ORE:30
  - COAL_ORE:30
  - DIAMOND_ORE:10
IsTop:
  Blocks:
    HOPPER: 10
  Spawners:
    PIG: 1000
    VILLAGERGOLEM: 10000
help:
  - '&7&m-----------------------------------------------------'
  - '%centered%&6&lIsland Help'
  - '&7&m-----------------------------------------------------'
  - '&e/is create &8- &7Create your own island.'
  - '&e/is invite &f<playerName> &8- &7Invite a player to your island.'
  - '&e/is list &8- &7View all players on your island.'
  - '&e/is top &8- &7View the richest Islands.'
  - '&e/is sethome &8- &7Set the home to your island.'
  - '&e/is home &8- &7Go to your island home.'
  - '&e/is leave &8- &7Leave your Island.'
  - '&e/is deinvite &f<playerName> &8- &7Revoke invitation to player.'
  - '&e/is kick &f<playerName> &8- &7Kick player from your Island.'
  - '&e/is leader &f<playerName> &8- &7Set player role to leader in your island.'
  - '&e/is chat &8- &7Switch to your Island chat.'
  - '&e/is warp &8- &7Opens the warp menu.'
  - '&e/is setwarp &8- &7Set a warp.'
  - '&e/is upgrades &8- &7Upgrade your island.'
  - '&e/is missions &8- &7Displays your daily Island Mission.'
  - '&e/is boosters &8- &7Boost your island using xp.'
  - '&e/is givecrystals <playername> <amount> &8- &7Give the specified player island crystals.'
  - '&e/is bypass &8- &7Bypass island restrictions.'
  - '&e/is version &8- &7Display current Island version.'
  - '&7&m-----------------------------------------------------'